version: "3.7"
services:
    mysql-db:
        image: '${MYSQL_IMAGE_NAME}'
        restart: always
        container_name: '${MYSQL_CONTSINER_NAME}'
        hostname: '${MYSQL_HOSTNAME}'
        working_dir: /var/www
        ports:
            - '${MYSQL_FORWARDING_PORT}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - mysql_data:/var/lib/mysql
    rts-app:
        image: '${APP_IMAGE_NAME}'
        restart: always
        container_name: '${APP_CONTSINER_NAME}'
        hostname: '${APP_HOSTNAME}'
        working_dir: /var/www
        depends_on:
            - mysql-db
        ports:
            - '${APP_FORWARDING_PORT}:80'
        volumes:
            - ./rts-app/.env:/var/www/rts-app/.env
            - ./rts-app/apache/rts-app.conf:/etc/apache2/sites-enabled/000-default.conf

    rts-web:
        image: '${WEB_IMAGE_NAME}'
        restart: always
        container_name: '${WEB_CONTSINER_NAME}'
        hostname: '${WEB_HOSTNAME}'
        working_dir: /var/www
        ports:
            - '${WEB_FORWARDING_PORT}:80'
        volumes:
            - ./rts-web/.env:/var/www/rts-web/.env
            - ./rts-web/apache/rts-web.conf:/etc/apache2/sites-enabled/000-default.conf
volumes:
    mysql_data:
    rts_app:
    rts_web:

networks:
    default:
        external: true
        name: cicd